// Automatically generated by astro-icon
// 66ec9975188fb338fb068a2c159e64ba71ce86c8706a8f364eaed69a39e104e7

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "preact"
		| "react"
		| "solid"
		| "svelte"
		| "vue";
}